### ISSUE TITLE
About the CacheRefreshRate

### ISSUE THREAD

**Issue by salt0107fish** [Ahmedest61/MRNetVLAD#5]
Hi! Thanks for your work.
When I try to train your model, I find it's slow to build cache. I want to know if I set the CacheRefreshRate to 0, will it affect the accuracy？
Thank you!

**Comment by oravus** [comment]
Hi @salt0107fish, `CacheRefreshRate` can affect accuracy. It mainly updates the stored descriptors used for negative mining.
